### ISSUE TITLE
Incorrect parsing stats dueling coasters

### ISSUE THREAD

**Issue by jochemvdmeulen** [fabianrguez/rcdb-api#7]
I was just looking at the json output of the api. I noticed that in dueling coasters most stats are a array with each element containing the stat for a separate track. However the names of all the tracks are contained in a single string. similar behaviour is present in the inversions stat, and the array of roller coaster elements also doesn't differentiate between tracks.
![GitHub2](https://github.com/fabianrguez/rcdb-api/assets/42549531/2a5de919-ef1b-4843-80f5-79f9efca6968)
https://rcdb-api.vercel.app/api/coasters/558

I think it would be better if in case of dueling coasters that the stats object contains an array with elements representing each track instead of each individual stat containing an array

**Comment by fabianrguez** [comment]
Hi! First of all thank you for you reporting the issue with dueling stats. In the next update the scraper will take into account if the roller coaster being scraped is  of type dueling to store stats in an array format.
Best regards
