### ISSUE TITLE
Closing date missing

### ISSUE THREAD

**Issue by PeterR87** [fabianrguez/rcdb-api#8]
I have been exploring the coasters json and i am missing the closing date for coasters that are no longer operating. For example:
![image](https://github.com/fabianrguez/rcdb-api/assets/51717512/dd9bc7b8-6216-4777-a158-6a440c1da8d6)
![image](https://github.com/fabianrguez/rcdb-api/assets/51717512/cec6c1de-b9c5-467a-a2fa-8c29093c2338)

Would be great if this could be added

Best regards,
Peter

**Comment by fabianrguez** [comment]
Hi! First of all thank you for you reporting the missing property. In the next update the status date will have an object of dates containing `opened` and `closed` date (this last one if it exists).

Best regards
